name: fenics
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics
  - matplotlib==3.7.1
  - pip>=20.1
  - pip:
    - sympy
    - sphinx_book_theme==1.1.0rc1
    - sphinx~=7
    - sphinx-design==0.4.1
    - sphinxcontrib-bibtex
