name: benchmark
on: [pull_request, push]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        mamba-version: "*"
        channels: conda-forge, defaults

    - name: Create Conda environment
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge fenics-dolfinx

    - name: Install local package and dependencies
      shell: bash -l {0}
      run: |
        pip install .[test]

    - name: Download previous benchmark data
      uses: actions/cache@v1
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: Run benchmark
      shell: bash -l {0}
      run: |
        pytest benchmark.py --benchmark-json output.json

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'pytest'
        output-file-path: output.json
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-on-alert: true
