name: CI
on: [pull_request, push]

jobs:
  run-on-conda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        mamba-version: "*"
        channels: conda-forge, defaults

    - name: Create Conda environment
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge fenics-dolfinx

    - name: Install local package and dependencies
      shell: bash -l {0}
      run: |
        pip install .[test]

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest test/ --cov festim --cov-report xml --cov-report term
    
    - name: Upload to codecov
      shell: bash -l {0}
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}

  run-on-docker:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Install local package and dependencies
        run: |
          pip install .[test]

      - name: Run tests
        run: |
          python3 -m pytest test/ --ignore=festim/_version.py --cov festim --cov-report xml --cov-report term

      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
