name: conda CI
on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        mamba-version: "*"
        channels: conda-forge, defaults

    - name: Create Conda environment
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge fenics-dolfinx

    - name: Install local package and dependencies
      shell: bash -l {0}
      run: |
        pip install .[test]

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest test/test_permeation_problem.py --cov festim --cov-report xml --cov-report term
    
    - name: Upload to codecov
      shell: bash -l {0}
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
