name: CI
on: [push, pull_reqeuest]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:stable
    steps:
      - name: Install local package and dependencies
        run: |
          pip install .[test]

      - name: Run tests
        run: |
          python3 -m pytest test/ --cov festim --cov-report xml --cov-report term

      - name: Upload to codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}